logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
    root: INFO
    org.springframework: INFO
    com.example: DEBUG
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: clayster
